version: '3.8'

services:

  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    restart: on-failure
    volumes:
      - .:/home/app/web

  db:
    image: postgres:13.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - "5050:80"

volumes:
  postgres_data:
  pgadmin:
